### ISSUE TITLE
Warnings in Log: so-rcvbuf not granted - DNS resolution is not available

### ISSUE THREAD

**Issue by bjoern-vh** [sujiba/pihole-unbound-hyperlocal#11]
Hello,

thanks for this project. I am using it for a few months without any problems and it's great.

Just looking into my docker compose log file I see the following messages:
```
pihole  | Starting unbound
pihole  | [1717647849] unbound[314:0] warning: so-rcvbuf 1048576 was not granted. Got 425984. To fix: start with root permissions(linux) or sysctl bigger net.core.rmem_max(linux) or kern.ipc.maxsockbuf(bsd) values.
pihole  |   [✗] DNS resolution is currently unavailable
  [✗] DNS resolution is not available
```

I am current running Debian 12 Bookworm 64-Bit with Docker version 24.0.7, build afdd53b and Docker compose Docker Compose version v2.21.0. I am using a unprivileged user added to the docker group. The image is pulled to the newest version.

From my perspective all is working as expected. But I am not sure if this is correct because of the messages. Do I have to change something in my config?

My compose file:
```
---
services:
  pihole-unbound:
    image: ${IMAGE}
    container_name: ${NAME}
    hostname: ${HOSTNAME}
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "${HTTP_PORT}:80/tcp"
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${WEBPASSWORD}
      PIHOLE_DNS_: ${PIHOLE_DNS}
      DNSSEC: ${DNSSEC}
      CUSTOM_CACHE_SIZE: ${CUSTOM_CACHE_SIZE}
      DNS_BOGUS_PRIV: ${DNS_BOGUS_PRIV}
      DNS_FQDN_REQUIRED: ${DNS_FQDN_REQUIRED}
      TEMPERATUREUNIT: ${TEMPERATUREUNIT}
      WEBTHEME: ${WEBTHEME}
      FTLCONF_MAXDBDAYS: ${MAXDBDAYS}
      FTLCONF_DBINTERVAL: ${DBINTERVAL}
    volumes:
      - ./etc-pihole/:/etc/pihole/
      - ./etc-dnsmasq.d/:/etc/dnsmasq.d/
    restart: unless-stopped
```

My .env
```
IMAGE=sujiba/pihole-unbound-hyperlocal:latest
NAME=pihole
HOSTNAME=pihole
HTTP_PORT=81
TZ='Europe/Berlin'
WEBPASSWORD=***removed***
PIHOLE_DNS='127.0.0.1#5335'
DNSSEC=false
CUSTOM_CACHE_SIZE=10000
DNS_BOGUS_PRIV=true
DNS_FQDN_REQUIRED=true
TEMPERATUREUNIT=c
WEBTHEME=default-dark
MAXDBDAYS=30
DBINTERVAL=60
```

If further info is needed please let me know.

Thanks in advance!
